language: perl
arch:
 - arm64
matrix:
 include:
  - dist: xenial
    perl: 5.24
    env: DISPLAY=:123 USE_SUDO=
  - dist: bionic
    perl: 5.26
    env: DISPLAY=:123 USE_SUDO=
  - dist: focal
    perl: 5.32
    env: DISPLAY=:123 USE_SUDO=
  - dist: focal
    env: DISPLAY=:123 USE_SYSTEM_PERL=1 USE_SUDO=sudo
    language: minimal

branches:
 except:
  - /appveyor/
  - /github-actions/
  - /doozer/

before_install:
 - if [ "$USE_SYSTEM_PERL" = "1" ]; then sudo apt-get update -qq; sudo apt-get install -qq cpanminus; fi
 - sudo apt-get update -qq
 - sudo apt-get install -qq xvfb twm libx11-dev libfreetype6-dev libxft-dev libxcursor-dev
# need to install configure_requires manually
 - $USE_SUDO cpanm --quiet --notest Tk::MMutil
 - Xvfb :123 &
 - (sleep 10; env DISPLAY=:123 twm) &

install:
 - $USE_SUDO cpanm --quiet --installdeps --notest . || (cat $HOME/.cpanm/work/*/build.log; false)
 - '[ "$USE_SUDO" = "" ] || rm -f MYMETA.*'

script:
 - perl Makefile.PL && env HARNESS_TIMER=1 HARNESS_OPTIONS=j4:c make disttest
